### ISSUE TITLE
Not override 

### ISSUE THREAD

**Issue by phuongphally** [Mustafashahoud/MoviesApp#2]
Errors  e: `/MoviesApp/app/src/main/java/com/mustafa/movieapp/binding/FragmentDataBindingComponent.kt: (11, 5): 'getFragmentBindingAdapters' overrides nothing`

```java

package com.mustafa.movieapp.binding

import androidx.databinding.DataBindingComponent
import androidx.fragment.app.Fragment

/**
 * A Data Binding Component implementation for fragments.
 */
class FragmentDataBindingComponent(fragment: Fragment) : DataBindingComponent {
    private val adapter = FragmentBindingAdapters(fragment)
    override fun getFragmentBindingAdapters(): FragmentBindingAdapters = adapter
}



```

**Comment by Mustafashahoud** [comment]
Hi bro, what do you mean it does not override anything? it does override this method is same as:
`override fun getFragmentBindingAdapters(): FragmentBindingAdapters {
        return adapter
    }
`
You must build the project to get **DataBindingComponent** generated.
It is just a class that extends [DataBindingComponent](https://developer.android.com/reference/android/databinding/DataBindingComponent) for a fragment and that is for scooping purpose as well as you can use it while UI testing the fragment you can override  DataBindingComponent to return a fake BindingAdapter (mockBindingAdapter).
