### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rurimo** [Mustafashahoud/MoviesApp#3]
This repository looks you almost used the original author's codes..
But why did you remove all of the license comments in every file? Was that intended?

**Comment by Mustafashahoud** [comment]
Hi, I did use some code form the google sample Github and other GitHub called **skydoves**, but I don't think I have whole classes that are written by others, Most of the codes written by me. but I actually did not know that I need to keep the License. as it is open-source.
Most importantly I kept a sponsor for the original repo owner  **skydoves**

**Comment by rurimo** [comment]
Ah, thanks!
